### ISSUE TITLE
Twinkly Stars on second screen

### ISSUE THREAD

**Issue by LeonMusCoden** [TheIcyStar/TwinklyStars#1]
Is it possible to have the twinkly stars on other screens ?

**Comment by TheIcyStar** [comment]
I'm not too sure how rainmeter's multimonitor stuff works, but I was able to get the stars to show up by playing around with these variables. For this example I'm using two 1080p monitors:
TotalScreenAreaX=(total pixels of two monitors)
StartX=0 (May need to be -1920 or 0 depending on where the monitor is)
EndX=1920 (May need to be 1920 or 3840 depending on where the monitor is)

I understand this might be a late reply, but someone else that comes across this may find this helpful
